name: NPM Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
          run_install: true

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 21.x
          cache: "pnpm"

      - name: Build and package the extension into a zip artifact 
        run: pnpm package:chrome
