name: Build and Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-chrome-extension: 
    # maybe use a matrix to build for multiple browsers
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
    
    - name: Ensure version match
      run: |
        PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")

        if [ "${TAG_VERSION#v}" != "$PACKAGE_VERSION" ]; then
          echo "Tag version and package.json version do not match!"
          echo "Tag version: ${TAG_VERSION#v}"
          echo "package.json version: $PACKAGE_VERSION"
          exit 1
        else
          echo "Tag version and package.json version match!"
        fi
      env:
        TAG_VERSION: ${{ github.ref }}

    - name: Build
      run: |
        npm install
        npm run build
      env:
        BROWSER: chrome
        OUTPUT:  chrome-extension-${{ github.ref }}.zip

    - name: Archive chrome-extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: chrome-extension-${{ github.ref }}
        path: releases/chrome-extension-${{ github.ref }}.zip
  
  github-release:
    name: Create GitHub release
    needs: build-chrome-extension
    runs-on: ubuntu-latest
    steps:

    - name: Download chrome-extension artifact
      uses: actions/download-artifact@v2
      with:
        name: chrome-extension-${{ github.ref }}
        path: chrome-extension-${{ github.ref }}.zip

    - name: Create GitHub release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: chrome-extension-${{ github.ref }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chrome-web-store:
    name: Upload to Chrome Web Store
    needs: build-chrome-extension
    runs-on: ubuntu-latest
    steps:

    - name: Download chrome-extension artifact
      uses: actions/download-artifact@v2
      with:
        name: chrome-extension-${{ github.ref }}
        path: chrome-extension-${{ github.ref }}.zip

    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: chrome-extension-${{ github.ref }}.zip
        extension-id: learnit-plus-plus
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
    
    