name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2

      - name: Build and package the extension into a zip artifact 
        run: |
          bun install --frozen-lockfile
          bun package:chrome 
          # bun package:firefox
        # env:
        #   FIREFOX_EXT_ID: ${{ secrets.FIREFOX_EXT_ID }}
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
          # firefox-file: build/firefox-mv3-prod.zip
